# Use OpenJDK 8 on Alpine Linux
FROM openjdk:8-jdk-alpine

# Install wget and unzip
RUN apk add --no-cache wget bash unzip

# Set Tomcat environment
ENV TOMCAT_VER=9.0.80
ENV CATALINA_HOME=/usr/local/tomcat
ENV PATH=$CATALINA_HOME/bin:$PATH

# Download and install Tomcat
RUN wget https://downloads.apache.org/tomcat/tomcat-9/v$TOMCAT_VER/bin/apache-tomcat-$TOMCAT_VER.tar.gz \
    && mkdir -p $CATALINA_HOME \
    && tar xzf apache-tomcat-$TOMCAT_VER.tar.gz -C $CATALINA_HOME --strip-components=1 \
    && rm apache-tomcat-$TOMCAT_VER.tar.gz

# Copy the WAR built by CI into Tomcat
COPY target/IssuesandDeploymentTracker-0.0.1-SNAPSHOT.war $CATALINA_HOME/webapps/ROOT.war


# Expose Tomcat port
EXPOSE 8080

# Run Tomcat
CMD ["catalina.sh", "run"]
